- src/main/java/de/bonndan/nivio/input/dto/SourceReference.java
- src/main/java/de/bonndan/nivio/util/Mappers.java
- src/test/java/de/bonndan/nivio/input/LandscapeDescriptionFactoryTest.java
- src/test/java/de/bonndan/nivio/input/SourceReferencesResolverTest.java
- src/test/resources/example/example_extrafields.yml
> [#43] more versatile source reference configurations

- .gitignore
- src/test/java/de/bonndan/nivio/input/LandscapeDescriptionFactoryTest.java
- src/test/java/de/bonndan/nivio/input/SeedTest.java
> fix tests for windows

- src/main/app/package-lock.json
- src/main/app/package.json
- src/main/app/src/App.scss
- src/main/app/src/Components/HomeComponent/Home.scss
- src/main/app/src/Components/HomeComponent/Home.tsx
> material ui home dashboard poc

- src/main/java/de/bonndan/nivio/input/http/HttpService.java
- src/main/java/de/bonndan/nivio/output/LocalServer.java
- src/main/java/de/bonndan/nivio/output/icons/IconsController.java
- src/main/java/de/bonndan/nivio/output/icons/VendorIcons.java
- src/test/java/de/bonndan/nivio/output/LocalServerTest.java
> 171 url bugfix

- src/main/app/src/Components/LandscapeComponent/LandscapeDashboard/LandscapeDashboard.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeItem/LandscapeItem.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeMap/LandscapeMap.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeOverview/LandscapeOverview.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeOverview/LandscapeOverviewLayout.tsx
- src/main/app/src/utils/API/APIClient.ts
- src/main/java/de/bonndan/nivio/output/map/svg/SVGItem.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGItemTest.java
Please see if this is sufficient. You can obtain the item by its id, then parse the data-x and data-y field for coordinates.
> [#183] coordinates in data

- .github/workflows/ci.yml
add ci.yml workflow to test prs
> run ci on prs

- src/main/java/de/bonndan/nivio/output/map/PNGRenderCache.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGDocument.java
- src/test/java/de/bonndan/nivio/output/map/PNGRenderCacheTest.java
PNGRenderCacheTest: mock requests to "/icons/service.png"
PNGRenderCache & SVGDocument use "try-with-resources"
> fix PNGRenderCacheTest

- src/main/java/de/bonndan/nivio/api/ApiController.java
- src/main/java/de/bonndan/nivio/model/LandscapeImpl.java
> [#185] fix swagger docs

- src/main/java/de/bonndan/nivio/input/FileFetcher.java
- src/main/java/de/bonndan/nivio/util/URLHelper.java
- src/test/java/de/bonndan/nivio/util/URLHelperTest.java
> [#249] fix URLHelper.combine if absolute URLs are used

- .github/workflows/ci.yml
- pom.xml
- src/main/java/de/bonndan/nivio/assessment/kpi/KPIFactory.java
- src/main/java/de/bonndan/nivio/model/Labeled.java
ci.yml: use `--no-transfer-progress` instead of `"-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"`
minor changes
> recover lost commit: Update frontend-maven-plugin to v1.10.0 (5013cc9)

- src/main/app/src/Components/LandscapeComponent/LandscapeMap/LandscapeMap.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeOverview/LandscapeOverviewLayout.tsx
- src/main/app/src/Components/NotificationComponent/Notification.tsx
- src/main/app/src/utils/API/APIConfig.ts
- src/main/app/src/utils/API/BasePath.test.tsx
- src/main/app/src/utils/API/BasePath.ts
> [#255] util to handle base path stuff

- Dockerfile
`ENV JAVA_TOOL_OPTIONS="-Xmx400m"`
> Dockerfile add JAVA_TOOL_OPTIONS environment variable

- src/main/java/de/bonndan/nivio/observation/ObserverRegistry.java
- src/main/resources/application.yml
This is just a simple change to make polling frequency for changes configurable.
> configurable polling frequency

- src/main/java/de/bonndan/nivio/input/LabelToFieldProcessor.java
- src/test/java/de/bonndan/nivio/input/LabelToFieldProcessorTest.java
> [#266] label cleanup, writing prefixed labels to item labels

- src/main/app/src/Components/NotificationComponent/Notification.test.tsx
- src/main/app/src/Components/NotificationComponent/Notification.tsx
- src/main/app/src/Components/NotificationComponent/NotificationLayout.tsx
- src/main/app/src/interfaces.ts
> Remove map button if landscape is unknown

- src/main/app/src/Components/LandscapeComponent/LandscapeMap/LandscapeMap.scss
- src/main/java/de/bonndan/nivio/output/map/svg/SVGItemLabel.java
- src/main/resources/static/css/svg.css
> 261 svg tweaks

- src/main/java/de/bonndan/nivio/output/map/hex/GroupAreaFactory.java
- src/main/java/de/bonndan/nivio/output/map/hex/Hex.java
- src/main/java/de/bonndan/nivio/output/map/hex/HexMap.java
- src/main/java/de/bonndan/nivio/output/map/hex/PathFinder.java
- src/main/java/de/bonndan/nivio/output/map/svg/HexPath.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGDocument.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaFactory.java
- src/test/java/de/bonndan/nivio/output/map/hex/GroupAreaFactoryTest.java
- src/test/java/de/bonndan/nivio/output/map/hex/HexMapTest.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaOutlineFactoryTest.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaTest.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGRelationTest.java
> [#277] refactor: separate hex code better from svg code

- src/main/app/src/Components/LandscapeComponent/LandscapeAssessment/LandscapeAssessment.scss
- src/main/app/src/Components/LandscapeComponent/LandscapeAssessment/LandscapeAssessment.test.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeAssessment/LandscapeAssessment.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeDashboard/LandscapeDashboard.scss
- src/main/app/src/Components/LandscapeComponent/LandscapeDashboard/LandscapeDashboard.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeDashboard/LandscapeDashboardLayout.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeGroup/LandscapeGroup.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeItem/LandscapeItem.scss
- src/main/app/src/Components/LandscapeComponent/LandscapeItem/LandscapeItem.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeMap/LandscapeMap.tsx
- src/main/app/src/Components/LandscapeComponent/LandscapeUtils/utils.tsx
- src/main/app/src/Components/SearchComponent/SearchResult.tsx
- src/main/app/src/Components/SliderComponent/Slider.scss
- src/main/app/src/interfaces.ts
- src/main/java/de/bonndan/nivio/assessment/Assessable.java
- src/main/java/de/bonndan/nivio/assessment/StatusValue.java
- src/main/java/de/bonndan/nivio/model/Labeled.java
- src/test/java/de/bonndan/nivio/assessment/AssessableTest.java
- src/test/java/de/bonndan/nivio/assessment/StatusValueTest.java
> 287 assessment summary fix

- src/main/app/src/Components/Landscape/Modals/Item/Item.tsx
- src/main/app/src/Components/Landscape/Utils/utils.tsx
> [#364] not showing labels accordion if empty

- .github/workflows/ci.yml
> parallel tests

- src/main/app/src/Components/Landscape/Map/Map.tsx
- src/main/app/src/Components/Landscape/Search/Search.tsx
- src/main/app/src/Components/Navigation/Navigation.test.tsx
> 375 fix search locate

- docs/source/env_config.rst
- docs/source/output.rst
- src/main/app/src/App.test.tsx
- src/main/app/src/App.tsx
- src/main/app/src/Components/Events/Events.tsx
- src/main/app/src/Components/Landscape/Dashboard/StatusBarLayout.tsx
- src/main/app/src/Components/Landscape/Map/MapRelation/MapRelation.tsx
- src/main/app/src/Components/Landscape/Modals/Item/Item.tsx
- src/main/app/src/Components/Landscape/Overview/OverviewLayout.tsx
- src/main/app/src/Components/Landscape/Search/Search.tsx
- src/main/app/src/Components/Layout/Layout.tsx
- src/main/app/src/Components/Manual/Man.test.tsx
- src/main/app/src/Components/Manual/Man.tsx
- src/main/app/src/Components/Navigation/Navigation.tsx
- src/main/app/src/Components/StatusChip/StatusChip.tsx
- src/main/app/src/Ressources/styling/ComponentStyles.ts
- src/main/app/src/Ressources/styling/theme.ts
- src/main/app/src/index.tsx
- src/main/java/de/bonndan/nivio/api/Index.java
- src/main/java/de/bonndan/nivio/api/LinkFactory.java
- src/main/java/de/bonndan/nivio/config/ConfigurableEnvVars.java
- src/main/java/de/bonndan/nivio/config/NivioConfigProperties.java
- src/main/java/de/bonndan/nivio/output/icons/IconService.java
- src/main/resources/application.yml
- src/test/java/de/bonndan/nivio/config/NivioConfigPropertiesTest.java
closes #357 
improves several ui aspects
> 357 customer theme

- docs/source/env_config.rst
- src/main/app/yarn.lock
- src/main/java/de/bonndan/nivio/input/AppearanceProcessor.java
- src/main/java/de/bonndan/nivio/input/Seed.java
- src/main/java/de/bonndan/nivio/model/Landscape.java
- src/main/java/de/bonndan/nivio/output/icons/ExternalIcons.java
- src/main/java/de/bonndan/nivio/output/icons/IconService.java
- src/main/java/de/bonndan/nivio/output/layout/OrganicLayouter.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGDocument.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGPattern.java
- src/main/resources/static/css/dedica_map.css
- src/test/java/de/bonndan/nivio/output/RenderingTest.java
- src/test/java/de/bonndan/nivio/output/icons/ExternalIconsTest.java
- src/test/java/de/bonndan/nivio/output/icons/IconServiceTest.java
- src/test/java/de/bonndan/nivio/output/layout/OrganicLayouterTest.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGDocumentTest.java
- src/test/resources/example/dedica.yml
Also closes #393 
Dedica landscape is contained in DEMO mode. Contains fixes for "fill" feature.
> Dedica landscape

- src/main/app/src/Components/Manual/Man.test.tsx
- src/main/app/src/Components/Manual/Man.tsx
#449 scroll bar appears dynamically and Message aligned center
> 449 Manual Message style changed

- src/main/app/src/Components/Landscape/Modals/Item/Item.test.tsx
- src/main/app/src/Components/Landscape/Modals/Item/Item.tsx
- src/main/app/src/Components/StatusChip/StatusChip.test.tsx
#440  Fixed Undefined and written test case
> 440 null undefinded Fix In UI

- src/main/java/de/bonndan/nivio/output/layout/SubLayout.java
> [#460] revert to old repulsion value

- src/main/app/src/Components/Landscape/Overview/Overview.test.tsx
- src/main/app/src/Components/Landscape/Overview/Overview.tsx
- src/main/app/src/Components/Landscape/Overview/OverviewLayout.test.tsx
- src/main/app/src/Components/Landscape/Overview/OverviewLayout.tsx
closes #430 
Now when there is only one landscape present, ui will be routed to the landscape map page .
> 430 forward to landscape

- src/main/app/src/Components/Landscape/Map/Map.css
- src/main/app/src/Components/Landscape/Map/Map.tsx
- src/main/app/src/Components/Landscape/Map/MapRelation/MapRelation.tsx
> 438 disable centering

- src/main/java/de/bonndan/nivio/model/Group.java
- src/main/java/de/bonndan/nivio/model/LandscapeFactory.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGDimensionFactory.java
- src/main/java/de/bonndan/nivio/output/map/svg/SVGGroupArea.java
- src/test/java/de/bonndan/nivio/model/GroupFactoryTest.java
- src/test/java/de/bonndan/nivio/model/GroupTest.java
- src/test/java/de/bonndan/nivio/output/layout/AllGroupsLayoutTest.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGGroupAreaOutlineFactoryTest.java
> [#516] fix that default group "common" has no landscape identifier

- src/main/java/de/bonndan/nivio/api/ApiController.java
- src/main/java/de/bonndan/nivio/input/Indexer.java
- src/main/java/de/bonndan/nivio/input/dto/LandscapeDescription.java
- src/main/java/de/bonndan/nivio/model/Item.java
- src/main/java/de/bonndan/nivio/model/Landscape.java
- src/main/java/de/bonndan/nivio/search/ItemIndex.java
- src/main/java/de/bonndan/nivio/search/SearchDocumentFactory.java
- src/main/java/de/bonndan/nivio/search/SearchIndex.java
- src/main/java/de/bonndan/nivio/search/SearchIndexingEventListener.java
- src/test/java/de/bonndan/nivio/input/IndexerIntegrationTest.java
- src/test/java/de/bonndan/nivio/model/LandscapeTest.java
- src/test/java/de/bonndan/nivio/search/ItemIndexTest.java
- src/test/java/de/bonndan/nivio/search/SearchDocumentFactoryTest.java
- src/test/java/de/bonndan/nivio/search/SearchIndexingEventListenerTest.java
> 498 extend search

- docs/source/input.rst
- pom.xml
- src/main/java/de/bonndan/nivio/input/FileFetcher.java
- src/main/java/de/bonndan/nivio/input/ReadingException.java
- src/main/java/de/bonndan/nivio/input/Seed.java
- src/main/java/de/bonndan/nivio/input/dot/InputFormatHandlerDot.java
- src/main/java/de/bonndan/nivio/model/ItemFactory.java
- src/main/java/de/bonndan/nivio/model/Link.java
- src/test/java/de/bonndan/nivio/input/dot/InputFormatHandlerDotTest.java
- src/test/java/de/bonndan/nivio/model/ItemFactoryTest.java
- src/test/java/de/bonndan/nivio/output/map/svg/SVGDocumentTest.java
- src/test/resources/example/dedica.dot
- src/test/resources/example/dedica.yml
- src/test/resources/example/dedica_dot.yml
- src/test/resources/example/inout.yml
> 343 dot input

- docs/source/schema/Models/ItemDescription.rst
- docs/source/schema/spec.json
- pom.xml
- src/test/java/de/bonndan/nivio/ArchSpringBootTest.java
- src/test/java/de/bonndan/nivio/ArchTestSpringBoot.java
No beans  in Application class
> [#231] ArchUnit 

- src/main/java/de/bonndan/nivio/input/dto/GroupDescription.java
- src/main/java/de/bonndan/nivio/input/dto/ItemDescription.java
- src/main/java/de/bonndan/nivio/model/Labeled.java
- src/test/java/de/bonndan/nivio/model/LabeledTest.java
Fixes the "group has no team field" error
> group description has anySetter to accept arbitrary labels

- docs/source/assessment.rst
- docs/source/schema/Models/KPIConfig.rst
- docs/source/schema/spec.json
- src/main/app/src/interfaces.ts
- src/main/java/de/bonndan/nivio/assessment/kpi/AbstractKPI.java
- src/main/java/de/bonndan/nivio/assessment/kpi/CustomKPI.java
- src/main/java/de/bonndan/nivio/assessment/kpi/KPIConfig.java
- src/main/java/de/bonndan/nivio/assessment/kpi/LifecycleKPI.java
- src/test/java/de/bonndan/nivio/assessment/kpi/CustomKPITest.java
- src/test/java/de/bonndan/nivio/assessment/kpi/LifecycleKPITest.java
- src/test/resources/example/pet_clinic.yml
> [#562] message template for custom KPIs

- pom.xml
- src/test/java/de/bonndan/nivio/input/KubernetesTest.java
> 139 update spring

- docs/source/schema/Models/Branding.rst
- docs/source/schema/Models/GroupDescription.rst
- docs/source/schema/Models/InterfaceDescription.rst
- docs/source/schema/Models/ItemDescription.rst
- docs/source/schema/Models/KPIConfig.rst
- docs/source/schema/Models/LandscapeConfig.rst
- docs/source/schema/Models/LandscapeDescription.rst
- docs/source/schema/Models/LayoutConfig.rst
- docs/source/schema/Models/Link.rst
- docs/source/schema/Models/SourceReference.rst
- docs/source/schema/spec.json
- src/test/java/de/bonndan/nivio/SchemaGenerationTest.java
This fixes that openapi schemas and rst documents contain randomly sorted properties.
> fix for schema generation

- src/main/app/src/Components/Landscape/Dashboard/StatusBarLayout.tsx
- src/main/app/src/Components/Notification/Changes.tsx
- src/main/app/src/Components/Notification/Notification.tsx
- src/main/app/src/Context/LandscapeContext.tsx
- src/main/app/src/utils/testing/LandscapeContextValue.ts
- src/main/java/de/bonndan/nivio/notification/EventNotification.java
- src/main/java/de/bonndan/nivio/notification/MessagingService.java
- src/test/java/de/bonndan/nivio/notification/MessagingServiceTest.java
> [#753] fix for changes not showing

- .github/ISSUE_TEMPLATE/release.md
- pom.xml
- src/main/app/package.json
- src/main/app/src/Components/Landscape/Dashboard/StatusBarLayout.tsx
- src/main/app/src/Components/Notification/Changes.tsx
- src/main/app/src/Components/Notification/Notification.tsx
- src/main/app/src/Context/FrontendMappingContext.tsx
- src/main/app/src/Context/LandscapeContext.tsx
- src/main/app/src/utils/testing/LandscapeContextValue.ts
- src/main/java/de/bonndan/nivio/notification/EventNotification.java
- src/main/java/de/bonndan/nivio/notification/MessagingService.java
- src/test/java/de/bonndan/nivio/notification/MessagingServiceTest.java
- fix for showing changes
- fix for frontend-mapping
> Preparing Release 0.4.2 (Bugfix release 0.4.1)

- nivio-demo/readme.md
> [#674] updated demo readme

- src/main/app/src/Context/LandscapeContext.tsx
> Landscape maps are now reloaded regarding current landscape identifier

- pom.xml
- src/main/app/package.json
- src/main/app/yarn.lock
> 763 develop

- readme.md
See rendered readme at https://github.com/dedica-team/nivio/tree/103_readme
> [#103] updated readme

- src/main/app/src/Components/Landscape/Utils/MappedString.test.tsx
- src/main/app/src/Components/Landscape/Utils/MappedString.tsx
- src/main/app/src/Context/FrontendMappingContext.tsx
- src/main/app/src/utils/testing/FrontendMappingContextType.ts
- src/main/java/de/bonndan/nivio/api/ApiController.java
- src/main/java/de/bonndan/nivio/output/dto/FrontendMappingApiModel.java
- src/test/java/de/bonndan/nivio/api/ApiControllerTest.java
- src/test/java/de/bonndan/nivio/output/dto/FrontendMappingApiModelTest.java
> [#814] frontend mapping cleanup

- src/main/app/src/Components/Landscape/Modals/Group/Group.tsx
- src/main/app/src/Components/Landscape/Modals/Item/Item.tsx
- src/main/app/yarn.lock
> Change status message displaying in group and item

- pom.xml
- src/test/java/de/bonndan/nivio/input/kubernetes/CreateItemsTest.java
- src/test/java/de/bonndan/nivio/input/kubernetes/InputFormatHandlerKubernetesTest.java
Adresses several security issues mentioned on snyk.
> bumped deps, fix one k8s test

- src/main/java/de/bonndan/nivio/assessment/AssessableGroup.java
- src/main/java/de/bonndan/nivio/input/dto/ComponentDescription.java
- src/main/java/de/bonndan/nivio/input/dto/RelationDescription.java
- src/main/java/de/bonndan/nivio/model/Group.java
- src/main/java/de/bonndan/nivio/model/Item.java
- src/main/java/de/bonndan/nivio/model/Labeled.java
- src/main/java/de/bonndan/nivio/model/Landscape.java
- src/main/java/de/bonndan/nivio/model/Relation.java
- src/test/java/de/bonndan/nivio/model/LabeledTest.java
> [#844] concurrent labels

- src/main/java/de/bonndan/nivio/security/CustomOAuth2UserService.java
- src/test/java/de/bonndan/nivio/security/CustomOAuth2UserServiceTest.java
> [#858] missing name in token fix

- src/main/java/de/bonndan/nivio/model/GroupFactory.java
- src/main/java/de/bonndan/nivio/model/LandscapeFactory.java
- src/main/java/de/bonndan/nivio/util/SafeAssign.java
- src/test/java/de/bonndan/nivio/model/GroupFactoryTest.java
Replace null values with empty string instead of discarding the changese and keeping the old values
- builder.withName() isn't set to empty string since its necessary for the landscape. Its only replaced with a new value
> Replace null values with empty string instead of discarding the change
